### ISSUE TITLE
Bismark vs HiSAT2?

### ISSUE THREAD

**Issue by cjfields** [menghaowei/DETECT-Seq#1]
The Nature Methods paper (https://www.nature.com/articles/s41592-021-01172-w) describes the read alignment step using Bismark, but the workflow and code shown here [uses HiSAT2](https://github.com/menghaowei/Detect-seq/blob/1bf5b362ff947b5700bde3cda2c6c63d493f296b/snakemake/snk.01.from_fq_to_bam.hisat3n.py#L79).  Was there any reason for the switch?

**Comment by menghaowei** [comment]
> The Nature Methods paper (https://www.nature.com/articles/s41592-021-01172-w) describes the read alignment step using Bismark, but the workflow and code shown here [uses HiSAT2](https://github.com/menghaowei/Detect-seq/blob/1bf5b362ff947b5700bde3cda2c6c63d493f296b/snakemake/snk.01.from_fq_to_bam.hisat3n.py#L79). Was there any reason for the switch?

Hello, and thank you for your interest in our Detect-seq method. Because Detect-seq contains C-to-T conversion information, a conversion aligner such as Bismark is required. When we were working on the NM paper, Bismark was the only available conversion aligner, but it had a slow mapping efficacy. Zhang et al. developed the Hisat-3N conversion mapping aligner in 2022, which is based on Hisat2. After careful testing, Hisat-3N, in my opinion, reports identity results to Bismark but with far superior mapping efficacy. So Hisat-3N is recommaned here.

[Hisat-3N link](http://daehwankimlab.github.io/hisat2/hisat-3n/)

**Comment by cjfields** [comment]
Awesome, thanks for the quick explanation.  I thought it might be something like this but definitely wanted to check!
